AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Gateway integration with SQS
Outputs:
  ApiEndpoint:
    Description: Endpoint for this stage of the api
    Value: !Join
      - ''
      - - https://
        - !Ref 'APIGateway'
        - .execute-api.
        - !Ref 'AWS::Region'
        - .amazonaws.com/
        - dev
Parameters:
  validatorName:
    Type: String
    Default: EventTableValidator
  validateRequestBody:
    Type: String
    Default: true
  validateRequestParameters:
    Type: String
    Default: true
Resources:
  APIGateway:
    Properties:
      Description: API Endpoint to receive JSON payloads and queue in SQS
      Name: MDMAPIGateway
    Type: AWS::ApiGateway::RestApi
  APIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: sqs:SendMessage
                Effect: Allow
                Resource: 
                  - !GetAtt 'MDMQueue.Arn'
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: apig-sqs-send-msg-policy
      RoleName: mdm-sqs-send-msg-role
    
  EventTableModel:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      RestApiId: !Ref APIGateway
      ContentType: application/json
      Description: Schema for event table
      Name: EventTableModel
      Schema: 
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "type": "object",
          "title": "Event",
          "properties": {
            "source_system_name": {
              "type": "string"
            },
            "source_bucket": {
              "type": "string"
            },
            "destination_bucket": {
              "type": "string"
            },
            "persona": {
              "type": "string"
            },
            "expiration_timestamp": {
              "type": "string"
            },
            "email":{
              "type": "string"
            },
            "isencryption":{
              "type": "string"
              }
          },
          "required": [
            "source_system_name",
            "source_bucket",
            "destination_bucket",
            "persona",
            "expiration_timestamp",
            "email",
            "isencryption"
          ]
        }
  RequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: !Ref validatorName
      RestApiId: !Ref APIGateway
      ValidateRequestBody: !Ref validateRequestBody
      ValidateRequestParameters: !Ref validateRequestParameters
  MDMQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: 'mdm-logs-queue'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
  PolicySQS:
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:*
            Effect: Allow
            Principal: '*'
            Resource: '*'            
            Sid: Sid1251731803252
        Version: '2012-10-17'
      Queues:
        - !Ref 'MDMQueue'
    Type: AWS::SQS::QueuePolicy
  MDMPostMethod:
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Credentials: !GetAtt 'APIGatewayRole.Arn'
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: '200'
        PassthroughBehavior: NEVER
        RequestParameters:
          integration.request.header.Content-Type: '''application/x-www-form-urlencoded'''
        RequestTemplates:
          application/json: Action=SendMessage&MessageBody=$input.body
        Type: AWS
        Uri: !Join
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - :sqs:path/
            - !Ref 'AWS::AccountId'
            - /
            - 'mdm-logs-queue'
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: '200'
      RequestModels:
        application/json: !Ref EventTableModel
      ResourceId: !Ref 'logsResource'
      RequestValidatorId: !Ref RequestValidator
      RestApiId: !Ref 'APIGateway'
    Type: AWS::ApiGateway::Method
  logsResource:
    Properties:
      ParentId: !Ref 'MDMResource'
      PathPart: logs
      RestApiId: !Ref 'APIGateway'
    Type: AWS::ApiGateway::Resource
  prodDeployment:
    DependsOn: 
      -  MDMPostMethod
    Properties:
      RestApiId: !Ref 'APIGateway'
    Type: AWS::ApiGateway::Deployment
  prodStage:
    Properties:
      DeploymentId: !Ref 'prodDeployment'
      RestApiId: !Ref 'APIGateway'
      StageName: prod
    Type: AWS::ApiGateway::Stage
  MDMResource:
    Properties:
      ParentId: !GetAtt 'APIGateway.RootResourceId'
      PathPart: MDM
      RestApiId: !Ref 'APIGateway'
    Type: AWS::ApiGateway::Resource
# adding aws lambda and triggers
  MDMLambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/mdm-logs-lambda'
      RetentionInDays: 3
  MDMLambdaRole:
    Type: 'AWS::IAM::Role'
    DependsOn:
      - MDMQueue
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub 'mdm-lambda-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/mdm-logs-lambda:*:*'
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: 
                  - !GetAtt MDMQueue.Arn
              - Effect: Allow
                Action: 
                  - s3:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
              - Effect: Allow
                Action:
                  - glue:GetJobs
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:ListJobs
                  - glue:GetJobRuns
                  - glue:GetJob
                Resource: '*'
  MDMLambdaSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    DependsOn:
      - MDMQueue
      - MDMLogsLambda
    Properties:
      BatchSize: 5
      Enabled: true
      EventSourceArn: !GetAtt MDMQueue.Arn
      FunctionName: !GetAtt MDMLogsLambda.Arn
  MDMS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: pdp-ops-ppp-dev

  MDMLogsLambda:
    Type: 'AWS::Lambda::Function'
    DependsOn:
      - MDMLambdaRole
      - MDMLambdaLogGroup
    Properties:
      Description: 'SQS triggered lambda.'
      FunctionName: !Sub 'mdm-logs-lambda'
      Handler: index.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 30
      TracingConfig:
        Mode: Active
      Role: !GetAtt MDMLambdaRole.Arn
      Code:
        ZipFile: |
          from __future__ import print_function
          import boto3
          import datetime
          import json

          # current-date = datetime.date.today()
          def lambda_handler(event, context):
          # print(event)
            current_date = str(datetime.date.today())
            client = boto3.client('glue')
            for record in event['Records']:
              print("client-created")
              payload = json.loads(record["body"])
              source_system_name = str(payload["source_system_name"])
              source_bucket = str(payload["source_bucket"])
              destination_bucket = str(payload["destination_bucket"])
              persona = str(payload["persona"])
              expiration_timestamp = str(payload["expiration_timestamp"])
              email = str(payload["email"])
              isencryption = str(payload["isencryption"])
              print("paylaod proceesed")
              
              JobNameValue = 'MDM_Mask_Enc_Data_Job'

              response = client.start_job_run(
                JobName=JobNameValue,
                Arguments={
                    '--source_system_name': source_system_name,
                    '--source_bucket': source_bucket,
                    '--destination_bucket': destination_bucket,
                    '--persona': persona,
                    '--expiration_timestamp': expiration_timestamp,
                    '--email': email,
                    '--isencryption':isencryption
                },
                #AllocatedCapacity=2,
                Timeout=5,
                #MaxCapacity=3,
                #SecurityConfiguration='string',
                NotificationProperty={
                    'NotifyDelayAfter': 5
                },
                WorkerType='Standard',
                NumberOfWorkers=5
              )
            
            return "pass"
  #Spark Job creation
  MDMGlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "sparkjob_mdm_role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - s3:*
                  - s3-object-lambda:*
                Resource: "*"
  #create a glue job for data-encryption
  MDMDataMask:
    Type: AWS::Glue::Job
    Properties:
      Role: !GetAtt MDMGlueServiceRole.Arn
      Description: Encrypt/Mask the PII Information based on the input from API call
      Command:
        Name: glueetl
        ScriptLocation:
          s3://mdm-govern-data-test/sourcecode/mdm_Mask_or_Encrypt_PII_Value.py
      AllocatedCapacity: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      Name: MDMDataEncryption

  #create basic role for execution and log of lambda function
  LambdaBasicRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaBasicRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:AddLayerVersionPermission
                  - s3:*
                  - s3-object-lambda:*
                  - ses:*
                Resource: '*'  
#Log group to capture logs for the delete s3 object after expiry and send email to the bucket expires in 5 days lambda function 
  Mydeletes3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
        LogGroupName: '/aws/lambda/lvemailanddeletes3lambfunc'
        RetentionInDays: 1
#Lambda function to delete the expired s3 objects and send email to the bucket expires in 5 days with scheduled event trigger
  deleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Cloud event triggered lambda to delete expired s3 bucket
      FunctionName: lvemailanddeletes3lambfunc
      Handler: emailanddeletes3_lambdafunction.lambda_handler
      Runtime: python3.9
      Layers: 
        - arn:aws:lambda:us-west-2:785368447960:layer:pymysqllayer:1
      Role: !GetAtt LambdaBasicRole.Arn
      CodeUri: s3://mdm-govern-data-test/sourcecode/emailanddeletes3_lambdafunction.zip
      Events:
        ScheduledEvent:
          Name: Every5min
          Type: Schedule
          Properties:
            Schedule: rate(1440 minutes)